import { DirectionProvider } from "@/components/ui/direction";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { IBM_Plex_Sans_Arabic, IBM_Plex_Sans } from "next/font/google";
import { notFound } from "next/navigation";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/features/shared/components/navbar";
import Footer from "@/features/shared/components/footer";
import QueryProvider from "@/providers/query-provider";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-ibm-plex-sans-arabic",
  weight: ["400", "500", "600", "700"],
});

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }
  setRequestLocale(locale);
  const messages = await getMessages();

  const font = locale === "ar" ? ibmPlexSansArabic : ibmPlexSans;

  return (
    <html
      lang={locale}
      className={`${font.className} `}
      suppressHydrationWarning
    >
      <body dir={locale === "ar" ? "rtl" : "ltr"}>
        <QueryProvider>
          <NextIntlClientProvider messages={messages}>
            <DirectionProvider dir={locale === "ar" ? "rtl" : "ltr"}>
              <Navbar />
              {children}
              <Footer />
              <Toaster dir={locale === "ar" ? "rtl" : "ltr"} richColors position="top-right" />
            </DirectionProvider>
          </NextIntlClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
